### PR TITLE
Update to play 2.8.1

### PR DESCRIPTION
**Pull request by mrdziuban**

### CODE REVIEW

**Comment by mrdziuban** [comment]
This also drops support for scala 2.11 since play 2.8 doesn't support it. I see that @gpgekko has a fork with similar changes (plus some others -- https://github.com/fkoehler/play-html-compressor/compare/master...gpgekko:update-play). Not sure if they're interested in merging those back upstream, but I'd be happy to close this if so.

**Comment by gpgekko** [comment]
Honestly I had forgotten all about that. I made it a while back so we could update one of our internal applications to the release candidate and see what would break. I haven't been working on that project for a few months now and don't really have time to look over it, test it and clean it up. If it is of interest to anyone I can open up a pull request.
One thing I do remember is that I had a lot of trouble with Coursier and I'm not sure if I ever went further with that.

**Comment by fkoehler** [comment]
Sorry, seems I had notifications off. I'd prefer to merge the changes from @gpgekko. I will have a look at this later.

**Comment by mrdziuban** [comment]
That would be great @fkoehler, let me know if I can help in any way.

**Comment by fkoehler** [comment]
Closed via #2

**Comment by fkoehler** [comment]
I have released version 2.8.0. Might take some time to sync into central repo.

**Comment by mrdziuban** [comment]
Perfect, thanks!

**Pull request closed without merging**
